### ISSUE TITLE
Test online judges API's to be used

### ISSUE THREAD

**Issue by gerardogalvez** [osdagoso/CoProManager#3]
[uHunt](https://uhunt.onlinejudge.org/api) and [uHunt LA](https://icpcarchive.ecs.baylor.edu/uhunt/api) (for UVa and ICPC Live Archive respectively) have been selected as the online judges APIs to be used for this project.

**Comment by gerardogalvez** [comment]
## Available problems
### UVA
https://uhunt.onlinejudge.org/api/p
### ICPC Live Archive
https://icpcarchive.ecs.baylor.edu/uhunt/api/p

Example:
```
[
  [
    5215,                   0   -> Problem ID
    13291,                  1   -> Problem Number
    "Frosting on the Cake", 2   -> Problem Title
    75,                     3   -> Number of Distinct Accepted User
    10,                     4   -> Best Runtime of an Accepted Submission
    1000000000,             5   -> Best Memory used of an Accepted Submission
    0,                      6   -> Number of No Verdict Given (can be ignored)
    0,                      7   -> Number of Submission Error
    0,                      8   -> Number of Can't be Judged
    0,                      9   -> Number of In Queue
    56,                     10  -> Number of Compilation Error
    0,                      11  -> Number of Restricted Function
    13,                     12  -> Number of Runtime Error
    0,                      13  -> Number of Output Limit Exceeded
    45,                     14  -> Number of Time Limit Exceeded
    0,                      15  -> Number of Memory Limit Exceeded
    129,                    16  -> Number of Wrong Answer
    1,                      17  -> Number of Presentation Error
    131,                    18  -> Number of Accepted
    5000,                   19  -> Problem Run-Time Limit (milliseconds)
    1,                      20  -> Problem Status (0 = unavailable, 1 = normal, 2 = special judge)
    0,                      21  -> This field isn't documented (when querying a specific problem this field is called 'rej')
  ],
  ...
]
```

## Specific users' submissions on specific problems
### UVA
https://uhunt.onlinejudge.org/api/subs-pids/{user-ids-csv}/{pids-csv}/{min-subs-id}
### ICPC Live Archive
https://icpcarchive.ecs.baylor.edu/uhunt/api/subs-pids/{user-ids-csv}/{pids-csv}/{min-subs-id}
* {user-ids-csv} is the user ids presented as comma-separated-values.
* {pids-csv} is the problem ids presented in comma-separated-values.
* {min-subs-id} is the minimum submission id to be returned (that is, to show all submissions set this value to zero, to see latest submissions, set it higher as appropriate).

The result is a hash map with the key is the user id and the value is the submissions of that user that associated with one of the specified problem ids.

Example: https://uhunt.onlinejudge.org/api/subs-pids/339/36,37/0
```
{
  "339": {
    "name": "Felix Halim",
    "uname": "felix_halim",
    "subs": [
      [
        558544,     0   -> Submission ID
        37,         1   -> Problem ID
        80,         2   -> Verdict ID
        80,         3   -> Runtime
        1000571585, 4   -> Submission Time (unix timestamp)
        4,          5   -> Language ID
        -1          6   -> Submission Rank
      ],
      [
        1554904,
        36,
        90,
        2514,
        1051719020,
        1,
        65846
      ],
      ...
    ]
  }
}
```
## Language ID
1.  ANSI C
2. Java
3. C++
4. Pascal
5. C++11
## Verdict ID
10. Submission error
15. Can't be judged
20. In queue
30. Compile error
35. Restricted function
40. Runtime error
45. Output limit
50. Time limit
60. Memory limit
70. Wrong answer
80. PresentationE
90. Accepted

**Comment by guillermoAMS** [comment]
### User ID
The way UVA saves their data is through an _user ID_ which is different from the _username_. In order to get this _user id_ and process the data correctly, we' need to use the following service:

[/api/uname2uid/{uname}.](url)

With the following parameters:
- {uname} is the username we want to convert into the _user id_

The service will return the user id that corresponds to the username provided.
