### ISSUE TITLE
View User's Statistics (Admin/User)

### ISSUE THREAD

**Issue by osgonz** [osdagoso/CoProManager#54]
Checkboxes in Users List will be activated for all users. The Ban/Unban buttons will be shown only for admin users. A new button shall be added: Compare (for admin users) / Compare With (for regular users).

Selecting at least one user from the list and clicking on this new button will open a modal window. Users will then be able to choose from a dropdown of contests (populated by a list of contests where all selected users participated together) to get the following statistics:
- [ ] Comparative table of problems and users (who solved which problem)
- [x] Who solved most problems
- [ ] Who was quickest to solve a problem (with time lapse)
- [x] Who had the highest accepted submissions/submissions ratio

@gerardogalvez or anyone else, feel free to add any others (go wild).

**Comment by HumbertoGuevara** [comment]
All 4 statistics are obtained in the back-end, but only the second and last ones are sent to the front-end.
